const productsData = [
  {
    id: 1,
    title: "Sneaker",
    description: "Red Sneaker Nike",
    img: "red-sneaker.jpg",
    country: "Japan",
    price: "100$",
    category: "Shoes",
  },
  {
    id: 2,
    title: "Sneaker",
    description: "White-orange Sneaker Nike",
    img: "white-sneaker.jpg",
    country: "Germany",
    price: "120$",
    category: "Shoes",
  },
  {
    id: 3,
    title: "Pizza",
    description: "Pizza have ingredients, such as tomatoes, cheese, ham, sauce",
    img: "pizza.jpg",
    country: "Italy",
    price: "20$",
    category: "Food",
  },
  {
    id: 4,
    title: "Suit",
    description: "Dark-Blue Suit",
    img: "blue-suit.jpg",
    country: "Switzerland",
    price: "1000$",
    category: "Clothes",
  },
  {
    id: 5,
    title: "Sneaker",
    description: "Lime Sneaker Nike",
    img: "lime-sneaker.jpg",
    country: "Germany",
    price: "100$",
    category: "Shoes",
  },
  {
    id: 6,
    title: "Rools",
    description:
      "Rolls have ingredients, such as rice, salmon, cucumber, avocado.",
    img: "rolls.jpg",
    country: "Japan",
    price: "25$",
    category: "Food",
  },
  {
    id: 7,
    title: "Television",
    description: "Television Dark Samsung",
    img: "television.jpg",
    country: "France",
    price: "400$",
    category: "Technique",
  },
  {
    id: 8,
    title: "MacBook",
    description: "MacBook Gray",
    img: "macbook.jpg",
    country: "USA",
    price: "500$",
    category: "Technique",
  },
  {
    id: 9,
    title: "Iphone",
    description: "Iphone XS + Black case(gift)",
    img: "iphone-xs.jpg",
    country: "USA",
    price: "400$",
    category: "Technique",
  },
  {
    id: 10,
    title: "Sweater",
    description: "Sweater White",
    img: "white-sweater.jpg",
    country: "Switzerland",
    price: "150$",
    category: "Clothes",
  },
  {
    id: 11,
    title: "Cake",
    description: "Chocolate Cake",
    img: "cake.jpg",
    country: "Belgium",
    price: "25$",
    category: "Food",
  },
];

export { productsData };
